apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-dcl1
  namespace: tracking
  labels:
    app: tracking-dcl1
    version: v1
    app.kubernetes.io/name: tracking-dcl1
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-dcl1
      version: v1
      app.kubernetes.io/name: tracking-dcl1
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app: tracking-dcl1
        version: v1
        app.kubernetes.io/name: tracking-dcl1
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: tracking
          image: 172.16.200.26/quality/tracking
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: tracking-dcl1-config
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "512Mi"
              cpu: "200m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-dcl1
  namespace: tracking
  labels:
    app: tracking-dcl1
    version: v1
    app.kubernetes.io/name: tracking-dcl1
    app.kubernetes.io/version: v1
spec:
  selector:
    app: tracking-dcl1
    version: v1
    app.kubernetes.io/name: tracking-dcl1
    app.kubernetes.io/version: v1
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32334
  type: NodePort

