tracking:
  unit: cp1
  data-storage: true

server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: tracking
  profiles:
    active: @env@

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wisdri.tracking
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mqtt:
  client-id: tracking-service-client
  completion-timeout: 3000
  qos: 1
  clean-session: false
  connection-timeout: 10
  keep-alive-interval: 20

rocketmq:
  producer:
    topic: tracking-data-fifo-topic
    request-timeout: 3
    max-attempts: 3
    ssl-enabled: false
  push-consumer:
    enabled: false
    topic: tracking-data-fifo-topic
    tag: "*"
    consumer-group: tracking-data-consumer-group
    request-timeout: 3
    ssl-enabled: false

cube-api:
  tree-root: "/aygg_tracking"
  connectTimeout: 3000
  readTimeout: 5000

time-series-storage:
  connectTimeout: 3000
  readTimeout: 5000
