# ========== 生产部署环境 ==========
# 中间件部署在开发服务器 172.16.203.x

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.203.30:5432/aygg_tracking
    username: postgres
    password: 123456

  redis:
    host: 172.16.203.18
    port: 6379
    password: Aygg@2026
    database: 0
    timeout: 5000

mqtt:
  host: tcp://172.16.203.11:1883
  username: "admin"
  password: "public"

rocketmq:
  producer:
    endpoints: 172.16.203.11:8081
  push-consumer:
    endpoints: 172.16.203.11:8081

cube-api:
  base-url: http://172.16.203.12:30800

time-series-storage:
  base-url: http://127.0.0.1:8886
