# ========== 本地调试环境 ==========
# 中间件部署在开发服务器 172.16.203.x

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aygg_tracking
    username: postgres
    password: postgres

  redis:
    host: localhost
    port: 6379
    password: Aygg@2026
    database: 0
    timeout: 5000

mqtt:
  url: tcp://172.16.203.11:1883
  username: "admin"
  password: "public"

rocketmq:
  producer:
    endpoints: localhost:8081
  push-consumer:
    endpoints: localhost:8081

cube-api:
  # mock地址, 改 zrm 1 的配置（新的 mqtt 订阅，cell_code），改 cp \fcl\dcl 的 status 跟踪缓存点位配置
  base-url: http://127.0.0.1:4523/m1/8137528-7895686-default
  # base-url: http://172.16.203.12:30800

time-series-storage:
  base-url: http://localhost:8886

quality:
  base-url: http://127.0.0.1:1234