apiVersion: v1
kind: ConfigMap
metadata:
  name: tracking-csl1-config
  namespace: tracking
data:
  # ----- 全局配置 -----

  TRACKING_UNIT: "csl1"
  TRACKING_STORAGE_ABNORMAL_ENABLED: "true"
  TRACKING_STORAGE_TRACKINGRESULT_ENABLED: "true"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://172.16.203.30:5432/aygg_tracking"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "123456"

  SPRING_REDIS_HOST: "172.16.203.18"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_PASSWORD: "Aygg@2026"
  SPRING_REDIS_DATABASE: "0"

  MQTT_CLIENTID: "tracking-csl1-client"
  MQTT_URL: "tcp://172.16.203.11:1883"
  MQTT_USERNAME: "admin"
  MQTT_PASSWORD: "public"

  ROCKETMQ_PUSHCONSUMER_CONSUMERGROUP: "tracking-data-consumer-group-csl1"
  ROCKETMQ_PUSHCONSUMER_TAG: "csl1"
  ROCKETMQ_PRODUCER_ENDPOINTS: "172.16.203.11:8081"
  ROCKETMQ_PUSHCONSUMER_ENDPOINTS: "172.16.203.11:8081"

  CUBEAPI_BASEURL: "http://172.16.203.12:30800"

  TIMESERIESSTORAGE_BASEURL: "http://quality-ts:8080"
